### PR TITLE
Jenkins Pipeline support

### PR DESCRIPTION
**Pull request by solevic**
Enables support for plugin jenkinsFile usage.

TODO: We need to find a way to get or generate the changelog through Run instead of AbstractBuild.

### CODE REVIEW

**Comment by solevic** [comment]
Here's some insight on how we could proceed to rebuild the ChangeSet

https://stackoverflow.com/questions/31247149/get-changeset-function-from-run-class-jenkins

**Comment by egor-n** [comment]
@solevic seems like this is the only way to get changelog from `Run`. HockeyApp plugin [does it too](https://github.com/jenkinsci/hockeyapp-plugin/blob/e719ed5a41f02533542bac03f7a4c44bb6d32bf2/src/main/java/hockeyapp/HockeyappRecorder.java#L431-L500).

**Comment by solevic** [comment]
@egor-n I tried adding the described method to the code, but my pipeline job is not an instance of AbstractProject so I cannot get the changeSet of my last build.

Here are the super types of my job.

Job test-fabric is not AbstractProject
class org.jenkinsci.plugins.workflow.job.WorkflowJob
class hudson.model.Job
class hudson.model.AbstractItem
class hudson.model.Actionable
class hudson.model.AbstractModelObject
class java.lang.Object

**Comment by solevic** [comment]
Ok it's done, you might want to squash these nasty commits though.

**Comment by egor-n** [comment]
Looks fine to me – can you add a "Pipeline usage" section to the readme file?

**Comment by egor-n** [comment]
@solevic the pipeline snippet generator doesn't want to generate the step. Instead, it outputs `step <object of type fabric.beta.publisher.FabricBetaPublisher>`. Can you take a look at this? If it's a simple fix, then we might want to include it into this PR.

**Comment by solevic** [comment]
@egor-n The pipeline snippet generator bug is fixed.
I also added the build result state in case of upload failure.

I'm not sure quite sure what to add to the README, could you take care of that part?

**Comment by egor-n** [comment]
Thank you!

**Comment by jlcvp** [comment]
Hi @egor-n and @solevic!

Could you please give us a short description on how to use the plugin on pipeline scripts?

**Pull request merged**
